name: "Peter Aylett's Blog"
favicon: null
layout_spectrum: 0.24972
typography_spectrum: 1
title: Peter Aylett Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#989898'
    - '#f9f9f9'
    - '#303030'
    - '#080c11'
    - '#5d5d5d'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
